# docker-compose.yml
version: "3.7"

services:
  mercure:
    image: dunglas/mercure:v0.11
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    # Development mode:
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "3000:3000"
